### ISSUE TITLE
ENV vars are not effective if config does not contain default values

### ISSUE THREAD

**Issue by Alexander-Krause** [frenos/btl44#10]
I have a BaseConfig with the ServerName "My Server Public". I want to use this config for 3 servers and only reset the ServerName via ENV var. However, the sed pattern assumes the ServerName is the default value "COMMUNITY SERVER".

I suggest to change the patterns and look only for strings with a following equal sign, e.g.:
```
sed -i "/ServerName=/c ServerName=$SERVERNAME" ./DefaultGame.ini
```

Same for PlayMode.

**Comment by frenos** [comment]
Correct, I initially used the "COMMUNITY SERVER" to get the right line as there are more lines with ServerName=.
Just tested it and the server seems to ignore the other entries completely.
I will push a fix right now.
